package Telas;

import Classes.SessionManager;
import DAO.ItemOrcamentoDAO;
import DAO.ProdutoDAO;
import javax.swing.JOptionPane;
import org.hibernate.Session;
import org.hibernate.Transaction;

/**
 *
 * @author daniel
 */
public class ProdutoGUI extends javax.swing.JFrame {
    
    private static ProdutoGUI instance;
    private static OrcamentoGUI orcamentoGUI;
    /**
     * Creates new form TelaNovoProduto
     */
    public ProdutoGUI() {
        initComponents();
        
        setLocationRelativeTo(null); // Centraliza a janela na tela
        
        // Ajusta para fechar apenas a janela atual
        setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
        
        // Adiciona os listeners para atualizar o subtotal
        addListeners();
    }
    
    // Método para obter a instância única da tela
    public static ProdutoGUI getInstance() {
        if (instance == null) {
            instance = new ProdutoGUI();
        }
        return instance;
    }

    private long idOrcamentoGlobal;
    
    
    // Método para abrir a tela de novo Produto
    public static void abrirNovaInstancia(OrcamentoGUI instanciaOrcamento) {
        orcamentoGUI = instanciaOrcamento;
        if (instance == null) {
            instance = new ProdutoGUI();
            // Define a janela como sempre no topo
            //instance.setAlwaysOnTop(true);
        }
        instance.setVisible(true);
        instance.requestFocus(); // Garante que a janela receba o foco
    }
    
    // Método para limpar os campos de texto
    private void limparCampos() {
        txtDescricao.setText("");
        txtValorUn.setText("");
        txtQuantidade.setText("");
        lblSubtotal.setText("R$0,00");
    }
    
    private void atualizarSubtotal() {
        try {
            double valorUnitario = Double.parseDouble(txtValorUn.getText().replace(",", "."));
            int quantidade = Integer.parseInt(txtQuantidade.getText());
            double subtotal = valorUnitario * quantidade;
            lblSubtotal.setText(String.format("R$%.2f", subtotal));
        } catch (NumberFormatException e) {
            lblSubtotal.setText("R$0,00");
        }
    }
    
    private void addListeners() {
        txtValorUn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                atualizarSubtotal();
            }
        });

        txtQuantidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                atualizarSubtotal();
            }
        });
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDescricao = new javax.swing.JLabel();
        lblValorTotal = new javax.swing.JLabel();
        lblQuantidade = new javax.swing.JLabel();
        lblValorUn = new javax.swing.JLabel();
        btnInserirProduto = new javax.swing.JButton();
        lblCancelar = new javax.swing.JButton();
        txtDescricao = new javax.swing.JTextField();
        lblSubtotal = new javax.swing.JLabel();
        txtValorUn = new javax.swing.JFormattedTextField();
        txtQuantidade = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Incluir Mercadoria");

        lblDescricao.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        lblDescricao.setText("Descrição da Peça / Mercadoria");

        lblValorTotal.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        lblValorTotal.setText("Total");

        lblQuantidade.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        lblQuantidade.setText("Quantidade");

        lblValorUn.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        lblValorUn.setText("Valor Unitário");

        btnInserirProduto.setText("Inserir Produto");
        btnInserirProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirProdutoActionPerformed(evt);
            }
        });

        lblCancelar.setText("Cancelar");
        lblCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblCancelarActionPerformed(evt);
            }
        });

        txtDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescricaoActionPerformed(evt);
            }
        });
        txtDescricao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDescricaoKeyTyped(evt);
            }
        });

        lblSubtotal.setText("R$0,00");

        txtValorUn.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtValorUnFocusLost(evt);
            }
        });
        txtValorUn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorUnActionPerformed(evt);
            }
        });
        txtValorUn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtValorUnKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtValorUnKeyTyped(evt);
            }
        });

        txtQuantidade.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        txtQuantidade.setText("1");
        txtQuantidade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtQuantidadeFocusLost(evt);
            }
        });
        txtQuantidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtQuantidadeKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQuantidadeKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDescricao)
                    .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblValorUn)
                            .addComponent(txtValorUn, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(lblQuantidade)
                                        .addGap(46, 46, 46))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblValorTotal)
                                    .addComponent(lblSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(btnInserirProduto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblDescricao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValorUn)
                    .addComponent(lblQuantidade)
                    .addComponent(lblValorTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtValorUn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCancelar)
                    .addComponent(btnInserirProduto))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblCancelarActionPerformed
        dispose(); // Fecha a janela
    }//GEN-LAST:event_lblCancelarActionPerformed

    private long salvarProduto() {
        Session session = SessionManager.getInstance().getSession();
        Transaction transaction = session.beginTransaction();
        try {
            
            ProdutoDAO produto = new ProdutoDAO();
            long produtoId = produto.findNextId(session);
            
            String descricaoProduto = txtDescricao.getText();
            
            
            String comandoSqlProduto = "insert into produtos(id_produto, descricao, tipo_produto) values (" + produtoId + ",'" + descricaoProduto + "', " +  "'Mercadoria')";
            session.createNativeQuery(comandoSqlProduto).executeUpdate();
            
            transaction.commit();  
            return produtoId;
        } catch (Exception ex) {
            //se der erro, dá um rollback na transação
            transaction.rollback();
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Erro ao salvar produto: " + ex.getMessage());
            return 0;
        }
        
    }
    
    
    private void salvarOrcamentoItem() {
        long produtoId = salvarProduto();
        Session session = SessionManager.getInstance().getSession();
        Transaction transaction = session.beginTransaction();
        try {
            ItemOrcamentoDAO itemOrcamento = new ItemOrcamentoDAO();
            long itemOrcamentoId = itemOrcamento.findNextId(session);
            
            // pega o valor unitário e substitui a vírgula por ponto para não dar erro no comando do sql
            String valorUnitario =  txtValorUn.getText().replace(",", ".");
            String quantidade = txtQuantidade.getText();
            long idOrcamento = orcamentoGUI.idOrcamentoGlobal;
            
            String comandoSqlOrcamentoItem = "insert into itens_orcamento(id_item_orcamento, preco_un, quantidade, id_orcamento, id_produto) values (" + itemOrcamentoId + "," + valorUnitario +" , " + quantidade + " , " + idOrcamento + " , " + produtoId + ")";
            session.createNativeQuery(comandoSqlOrcamentoItem).executeUpdate();
            
            transaction.commit();
            
        } catch (Exception ex) {
            //se der erro, dá um rollback na transação
            transaction.rollback();
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Erro ao salvar orcamento item: " + ex.getMessage());
        }

    }
    
            
    private void btnInserirProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirProdutoActionPerformed
        // TODO add your handling code here:
        
        if (txtDescricao.getText().trim().isEmpty() || txtValorUn.getText().trim().isEmpty() || txtQuantidade.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Os campos são obrigatórios.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
            
        } else{
            //Preciso pegar o idOrcamento para salvar o orçamento_item e depois o produto
            if (orcamentoGUI.idOrcamentoGlobal > 0) {
                salvarOrcamentoItem();
            }
            orcamentoGUI.atualizarGridItens();
            dispose(); 
            limparCampos();
            txtQuantidade.setValue(1);
        }
    }//GEN-LAST:event_btnInserirProdutoActionPerformed

    private void txtDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescricaoActionPerformed

    private void txtValorUnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorUnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorUnActionPerformed

    private void txtDescricaoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescricaoKeyTyped
        if (txtDescricao.getText().length() >= 50) {
            evt.consume(); // Limita o tamanho a 50 caracteres
        }
    }//GEN-LAST:event_txtDescricaoKeyTyped
    // Método para impedir a digitação de caracteres inválidos no campo de Valor Unitário
    private void txtValorUnKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorUnKeyTyped
        char c = evt.getKeyChar();

        // Permite apenas números e vírgula para valor decimal
        if (!Character.isDigit(c) && c != ',') {
            evt.consume(); // Impede a digitação de qualquer caractere que não seja número ou vírgula
        }

        // Limita o tamanho do texto a 5 caracteres
        if (txtValorUn.getText().length() >= 5) {
            evt.consume(); // Limita o tamanho a 5 caracteres
        }     
    }//GEN-LAST:event_txtValorUnKeyTyped
    
    // Método para impedir a digitação de caracteres inválidos no campo de Quantidade
    private void txtQuantidadeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQuantidadeKeyTyped
        char c = evt.getKeyChar();

        // Permite apenas números
        if (!Character.isDigit(c)) {
            evt.consume(); // Impede a digitação de qualquer caractere que não seja número
        }

        // Limita o tamanho do texto a 5 caracteres
        if (txtQuantidade.getText().length() >= 5) {
            evt.consume(); // Limita o tamanho a 5 caracteres
        }
    }//GEN-LAST:event_txtQuantidadeKeyTyped

    private void txtValorUnKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorUnKeyReleased
        
    }//GEN-LAST:event_txtValorUnKeyReleased

    private void txtQuantidadeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQuantidadeKeyReleased
        
    }//GEN-LAST:event_txtQuantidadeKeyReleased
    
    // Quando o campo perder o foco, define o valor padrão como "0,00" se estiver vazio
    private void txtValorUnFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtValorUnFocusLost
        if (txtValorUn.getText().trim().isEmpty()) {
            txtValorUn.setText("0,00"); // Define o valor padrão se estiver vazio
        } else {
            atualizarSubtotal(); // Atualiza o subtotal quando o campo perde o foco
        }
    }//GEN-LAST:event_txtValorUnFocusLost
    
    // Quando o campo perder o foco, define o valor padrão como "1" se estiver vazio
    private void txtQuantidadeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtQuantidadeFocusLost
        if (txtQuantidade.getText().trim().isEmpty()) {
            txtQuantidade.setText("1"); // Define o valor padrão se estiver vazio
        } else {
            atualizarSubtotal(); // Atualiza o subtotal quando o campo perde o foco
        }
    }//GEN-LAST:event_txtQuantidadeFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProdutoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProdutoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProdutoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProdutoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProdutoGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInserirProduto;
    private javax.swing.JButton lblCancelar;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblQuantidade;
    private javax.swing.JLabel lblSubtotal;
    private javax.swing.JLabel lblValorTotal;
    private javax.swing.JLabel lblValorUn;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JFormattedTextField txtQuantidade;
    private javax.swing.JFormattedTextField txtValorUn;
    // End of variables declaration//GEN-END:variables
}
