package Telas;

import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author daniel
 */
public class TelaImpressao extends javax.swing.JFrame {

    /**
     * Creates new form TelaImpressao
     */
    public TelaImpressao() {
        initComponents();
        
        paneListagem.setBorder(null);
        setAlwaysOnTop(true);
        setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);

        // Ocultando a coluna número
        TableColumnModel columnModel = tblListagem.getColumnModel();
        TableColumn column = columnModel.getColumn(0); // 0 é o índice da coluna
        column.setMinWidth(0);
        column.setMaxWidth(0);
        column.setPreferredWidth(0);
        column.setWidth(0);

    }
    
    // Métodos públicos para preencher os campos na tela de impressão
    public void setLblNumeroOrcamento(String numeroOrcamento) {
        lblNumeroOrcamento.setText(numeroOrcamento);
    }

    public void setLblNomeCliente(String nomeCliente) {
        lblNomeCliente.setText(nomeCliente);
    }

    public void setLblNomeVeiculo(String nomeVeiculo) {
        lblNomeVeiculo.setText(nomeVeiculo);
    }

    public void setLblPlacaVeiculo(String placaVeiculo) {
        lblPlacaVeiculo.setText(placaVeiculo);
    }

    public void setLblDataHoraOrcamento(String dataHoraOrcamento) {
        lblDataHoraOrcamento.setText(dataHoraOrcamento);
    }
    
    public void setLblValorTotal(String valorTotal) {
        lblValorTotal.setText(valorTotal);
    }
    
    // Método para carregar os dados da tabela
    public void carregarDadosTabela(List<Object[]> dados) {
        DefaultTableModel model = (DefaultTableModel) tblListagem.getModel();
        model.setRowCount(0); // Limpa a tabela antes de adicionar os dados

        for (Object[] row : dados) {
            model.addRow(row);
        }

        // Ajustar a altura da tabela e do painel
        ajustarAlturaTabela();
    }

    public void ajustarAlturaTabela() {
        int rowHeight = tblListagem.getRowHeight(); // Altura de uma linha
        int rowCount = tblListagem.getRowCount();  // Quantidade de linhas
        int headerHeight = tblListagem.getTableHeader().getHeight(); // Altura do cabeçalho
        int marginHeight = 10; // Margem adicional (pode variar conforme o layout)

        // Calcular altura total necessária (linhas + cabeçalho + margens)
        int tableHeight = (rowHeight * rowCount) + headerHeight + marginHeight;

        // Multiplicar por 2.1 como ajuste temporário
        int adjustedHeight = (int) (tableHeight * 2);

        // Ajustar tamanho preferido da tabela e do painel
        tblListagem.setPreferredScrollableViewportSize(
                new java.awt.Dimension(tblListagem.getPreferredScrollableViewportSize().width, adjustedHeight)
        );

        paneListagem.setPreferredSize(
                new java.awt.Dimension(paneListagem.getWidth(), adjustedHeight)
        );

        // Revalidar e repintar componentes
        paneListagem.revalidate();
        paneListagem.repaint();
        this.revalidate();
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNomeEmpresa = new javax.swing.JLabel();
        lblEndereco = new javax.swing.JLabel();
        lblFone = new javax.swing.JLabel();
        lblNumeroOrcamento = new javax.swing.JLabel();
        lblNomeCliente = new javax.swing.JLabel();
        lblDataHoraOrcamento = new javax.swing.JLabel();
        lblNomeVeiculo = new javax.swing.JLabel();
        lblPlacaVeiculo = new javax.swing.JLabel();
        lblValorTotal = new javax.swing.JLabel();
        paneListagem = new javax.swing.JScrollPane();
        tblListagem = new javax.swing.JTable();
        jLabel0 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblNomeEmpresa.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        lblNomeEmpresa.setForeground(new java.awt.Color(0, 0, 0));
        lblNomeEmpresa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNomeEmpresa.setText("VR AUTO CENTER");

        lblEndereco.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        lblEndereco.setForeground(new java.awt.Color(0, 0, 0));
        lblEndereco.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEndereco.setText("Rua Canadá 131, Nações, Indaial - SC");

        lblFone.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        lblFone.setForeground(new java.awt.Color(0, 0, 0));
        lblFone.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFone.setText("Fone, Whats: (47) 3394-3977");

        lblNumeroOrcamento.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        lblNumeroOrcamento.setText(" ");

        lblNomeCliente.setText(" ");

        lblNomeVeiculo.setText(" ");

        lblPlacaVeiculo.setText(" ");

        lblValorTotal.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        lblValorTotal.setText("R$ ");

        paneListagem.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        paneListagem.setMaximumSize(new java.awt.Dimension(0, 0));
        paneListagem.setMinimumSize(new java.awt.Dimension(0, 0));
        paneListagem.setPreferredSize(new java.awt.Dimension(0, 0));

        tblListagem.setFont(new java.awt.Font("Liberation Sans", 0, 15)); // NOI18N
        tblListagem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Número Item", "Descrição", "Valor Un.", "Qtd.", "Subtotal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblListagem.setShowGrid(false);
        paneListagem.setViewportView(tblListagem);

        jLabel0.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        jLabel0.setText("ORÇAMENTO Nº:");

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        jLabel1.setText("VALOR TOTAL:");

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        jLabel2.setText("Cliente:");

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        jLabel3.setText("Carro:");

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        jLabel4.setText("Placa:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNomeEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, 1048, Short.MAX_VALUE)
                    .addComponent(lblFone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(paneListagem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1048, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel0)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblNumeroOrcamento))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblNomeVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblPlacaVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblDataHoraOrcamento, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(lblNomeEmpresa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEndereco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFone)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel0)
                    .addComponent(lblNumeroOrcamento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)
                        .addComponent(lblNomeVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(lblPlacaVeiculo))
                    .addComponent(lblDataHoraOrcamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paneListagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblValorTotal))
                .addContainerGap(557, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaImpressao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaImpressao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaImpressao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaImpressao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaImpressao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel0;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblDataHoraOrcamento;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblFone;
    private javax.swing.JLabel lblNomeCliente;
    private javax.swing.JLabel lblNomeEmpresa;
    private javax.swing.JLabel lblNomeVeiculo;
    private javax.swing.JLabel lblNumeroOrcamento;
    private javax.swing.JLabel lblPlacaVeiculo;
    private javax.swing.JLabel lblValorTotal;
    private javax.swing.JScrollPane paneListagem;
    private javax.swing.JTable tblListagem;
    // End of variables declaration//GEN-END:variables
}
